### ISSUE TITLE
How to use guifg instead of guibg of CursorColumn.

### ISSUE THREAD

**Issue by wsdjeg** [e0da/dotfiles#19]
hi @justinforce 

I just read your answer here : https://stackoverflow.com/questions/2447109/showing-a-different-background-colour-in-vim-past-80-characters

I want to add a func to toggle highlight any character past the 80th column.

as you can see: my func is 
```viml
let s:fcflag = 0
function! s:toggle_fill_column() abort
    if !s:ccflag
        let &colorcolumn=join(range(80,999),",")
        let s:ccflag = 1
    else
        set cc=
        let s:ccflag = 0
    endif
endfunction
```

but CursorColumn only can change the background of text. and the color of character.

in vim what I see is  :

![2017-05-01-13 54 08](https://cloud.githubusercontent.com/assets/13142418/25573259/3d61b4d8-2e76-11e7-99ce-b52da3d71a5c.png)

in spacemacs what I see is:

![2017-05-01_1159x62](https://cloud.githubusercontent.com/assets/13142418/25573288/91b3b4aa-2e76-11e7-8069-7691c5721bf2.png)

**Comment by justinforce** [comment]
Hey! Thank you for reaching out, and I appreciate the care you took in preparing this question, but despite being an avid Vim user, I never mess much with VimScript. I'm afraid I can't help with this. Looks like there's a [stackexchange for vim](https://vi.stackexchange.com/), so I'd look for help there. Good luck!

**Comment by wsdjeg** [comment]
Thanks.
